### ISSUE TITLE
must i install hummingbot first?

### ISSUE THREAD

**Issue by lord-dubious** [cardosofede/hummingbot-deploy#5]
do i needt to create a humming bird instance from the offical repo and input my api key and import them before i can use this?

**Comment by cardosofede** [comment]
> do i needt to create a humming bird instance from the offical repo and input my api key and import them before i can use this?
> 
> 

Next week we are going to provide instructions that explains the setup.
For now just clone and run: bash setup.py

That will launch the dashboard and the backend api. If you want to trade you need to put the credentials under bots/credentials/master_account/

Soon we will add functionality to connect and encrypt the credentials from the dashboard
