### ISSUE TITLE
Log files and formatting

### ISSUE THREAD

**Issue by DutchOrange-1** [cardosofede/hummingbot-deploy#8]
These are the only minor issues I encountered when using the dashboard. So far loving it, works super well. 
Regarding the deployment of the bot, it would be nice to be able to make the collums bigger, to read the full name as can be seen in the image below
![cantSeeMuch](https://github.com/cardosofede/hummingbot-deploy/assets/54233804/e811e028-7f6c-439e-aaf4-7f0de22281c3)

After starting my bot It does not appear in the instances tab. It would be nice to have a progress bar/indication that the bot creation has started. As well as a place to find the log files on the dashboard (Maybe I am blind but I can't seem to find any log files)

**Comment by cardosofede** [comment]
thanks for the observation! I think that we already improved some part of this issues so if you can review and submit the updates will be great.
I was thinking that can be easy to organize the issues by page or category of pages, what do you think?
